Handle Docker validation error during sandbox run
Docker exception during the `sandbox run` command were not handled which resulted in throwing the exception to the user:

```
$ sandbox run 1.1.12
Error: Encountered unexpected error.
Error: Reason: DockerValidationError ['Docker is installed but not running.', 'Please start Docker with one of the Docker flavors based on your OS:', '  Linux:   Docker service', '  MacOS:   Docker for Mac', 'A successful Docker startup can be verified with: docker info']
Error: Further information of the error can be found in the error log file: /Users/mj/.conductr/errors.log
```

This PR fixes the handling so that only the appropiate error message is displayed:

```
$ sandbox run 1.1.12
Error: Docker is installed but not running.
Error: Please start Docker with one of the Docker flavors based on your OS:
Error:   Linux:   Docker service
Error:   MacOS:   Docker for Mac
Error: A successful Docker startup can be verified with: docker info
```