Hostname lookup validation
Adding additional check how long the hostname lookup takes. This validation is necessary to check if ConductR would fail at startup given this issue with Java 8 on macOS: https://github.com/akka/akka/issues/22160

The validation is calling a simple jar files that outputs the lookup time of `java.net.InetAddress.getLocalHost(InetAddress.java:1500)`. If the lookup takes longer than 3 seconds then the validation fails and the following validation error is thrown:

```
$ sandbox run 2.0.2
Error: Hostname lookup took 5006 milliseconds which will result in a ConductR startup failure
Error: This is known Java 8 issue on macOS: http://stackoverflow.com/questions/39636792/jvm-takes-a-long-time-to-resolve-ip-address-for-localhost
Error: To speed up the hostname lookup add your macOS hostname to /etc/hosts
Error: Resolves your hostname on the terminal with: hostname
Error: Sample /etc/hosts file:
Error: 127.0.0.1   localhost mbpro.local
Error: ::1         localhost mbpro.local
```

If the hostname is set in the `/etc/hosts` file then the lookup takes about 30 ms.

The check is only performed in sandbox JVM mode.