Set local_connection flag correctly
Prior to this PR the `local_connection` flag of the conduct command was only `false` if the `—ip` or `—host` args have been set, not if the `CONDUCTR_HOST` or `CONDUCTR_IP` envs have been set.

As a result, a failed conduct load command recommended to start the sandbox when the `CONDUCTR_HOST` or `CONDUCTR_IP` env was set to an external ConductR cluster. This PR fixes this issue.

** Prior output**

```
$ export CONDUCTR_HOST=10.10.10.10
$ conduct load visualizer
Retrieving bundle..
Loading bundle from cache typesafe/bundle/visualizer
Bintray credentials loaded from /Users/mj/.lightbend/commercial.credentials
Retrieving from cache /Users/mj/.conductr/cache/visualizer-v2-4bbf7b78508b53645eb4dc7b769e2643c5429767c187f284452905fa25e77b46.zip
Loading bundle to ConductR..
Error: Unable to contact ConductR.
Error: Reason: HTTPConnectionPool(host='10.10.10.10', port=9005): Max retries exceeded with url: /v2/bundles (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10fa4d7f0>: Failed to establish a new connection: [Errno 60] Operation timed out',))
Error: Start the ConductR sandbox with: sandbox run IMAGE_VERSION
```

** New output**

```
$ export CONDUCTR_HOST=10.10.10.10
$ conduct load visualizer
Retrieving bundle..
Loading bundle from cache typesafe/bundle/visualizer
Bintray credentials loaded from /Users/mj/.lightbend/commercial.credentials
Retrieving from cache /Users/mj/.conductr/cache/visualizer-v2-4bbf7b78508b53645eb4dc7b769e2643c5429767c187f284452905fa25e77b46.zip
Loading bundle to ConductR..
Error: Unable to contact ConductR.
Error: Reason: HTTPConnectionPool(host='10.10.10.10', port=9005): Max retries exceeded with url: /v2/bundles (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x1081cd780>: Failed to establish a new connection: [Errno 60] Operation timed out',))
Error: Make sure it can be accessed at http://10.10.10.10:9005/v2/bundles
```