Drop Docker machine support
The conductr-cli with the ConductR JVM approach will not support Windows anymore. Only for Windows 10 Home Edition and older Windows versions Docker machine is the recommended installation path on docker.com. Also, Docker for Mac is already out for more than 6 months.

Therefore, we going to drop Docker machine support. This also simplied the HAProxy implementation of the sandbox JVM approach, see https://github.com/typesafehub/conductr-cli/pull/245#issuecomment-273042918.

If the `DOCKER_MACHINE_NAME` environment variable is set then we throw now the following error when starting the sandbox:

```
$ sandbox run 1.1.12
Error: Docker machine envs are set but Docker machine is not supported by the conductr-cli.
Error: We recommend to use one of following the Docker distributions depending on your OS:
Error:   Linux:                                         Docker Engine
Error:   MacOS:                                         Docker for Mac
Error: For more information checkout: https://www.docker.com/products/overview
```