Validate bintray credentials on demand
So far have checked for valid Bintray credentials every time the sandbox has been started or a bundle has been loaded from Bintray.

Due to the fact that the ConductR artifcats are available on a public Bintray repository, we don’t need to perform this check every time. Also, every bundle is hosted on a public Bintray repository, including the monitoring bundles (https://bintray.com/lightbend/commercial-monitoring is also public). As a result, the user doesn’t need to setup Bintray credentials anymore from onwards ConductR 2.1.0.

This PR is:
- Adding a new validation to `sandbox_run_jvm` that checks based on the ConductR version if Bintray credentials are needed. If Bintray credentials are needed and the credential file is not created or malformed then the `sandbox run` command will abort before starting ConductR
- Changing the Bintray resolver so that no exception is thrown anymore if the credentials could not be loaded. Instead, we now try to download the artifacts without credentials. If a `404 Not Found` with the response text `Repo my-repo was not found` then we will catch this error and abort with the message:

```
$ conduct load lightbend/commercial-releases/ConductR-Agent-Debian
Retrieving bundle..
Loading bundle from cache lightbend/commercial-releases/ConductR-Agent-Debian
Error: Unable to find Bintray repository lightbend/commercial-releases. If this is a private repository make sure to setup the Bintray credentials at /Users/mj/.lightbend/commercial.credentials
```

Note that this message is only thrown for private Bintray repositories and after our `sandbox run` validation check. So for all ConductR artificats hosted on Bintray this error should never occur. The error should only occur in case the user wants to load bundles from a custom private repository.