Obtain and extract ConductR universal binaries
The new sandbox approach uses the ConductR universal binaries to start the core and agent processes.

This PR downloads the ConductR core and agent universal binaries from Bintray. First the local cache is interrogated for the presence of the binary. If the binary is not yet available within the local cache, then it will be downloaded from Bintray. If the binary is present within the local cache, they will be used instead.

The core and agent binaries are expanded into the `${image_dir}/core` and `${image_dir}/core`. The directories will be emptied before the binary is expanded.

## Handled error scenarios
The following error scenarios are handled with a descriptive error message (see test output):
- Bintray credential file can not be found
- Malformed Bintray credential file
- Bintray unreachable
- ConductR version on Bintray not found

This PR also improves the Bintray error handling on `conduct load`. When Bintray is unreachable, a descriptive error message is returned. Prior to this PR, an error was displayed saying that ConductR could not been started (which is the wrong error message for this case).

## Test output

### Downloading from Bintray

```
$ sandbox run 2.0.0-rc.2
Bintray credentials loaded from /Users/mj/.lightbend/commercial.credentials
Retrieving https://dl.bintray.com/lightbend/commercial-releases/conductr-2.0.0-rc.2.tgz
[#################################################] 100%
Retrieving https://dl.bintray.com/lightbend/commercial-releases/conductr-agent-2.0.0-rc.2.tgz
[#################################################] 100%
Extracting ConductR core to /Users/mj/.conductr/images/core
Extracting ConductR agent to /Users/mj/.conductr/images/agent
Binding ConductR core to the following address: 192.168.1.1
Binding ConductR agent to the following address: 192.168.1.1
```

### Using local cache

```
sandbox run 2.0.0-rc.2
Extracting ConductR core to /Users/mj/.conductr/images/core
Extracting ConductR agent to /Users/mj/.conductr/images/agent
Binding ConductR core to the following address: 192.168.1.1
Binding ConductR agent to the following address: 192.168.1.1
```

### Bintray credential file not found

```
$ sandbox run 2.0.0-rc.2
Error: Bintray credentials not found in /Users/mj/.lightbend/commercial.credentials
Error: Please follow the instructions to setup the Lightbend Bintray credentials:
Error:   http://developers.lightbend.com/docs/reactive-platform/2.0/setup/setup-sbt.html
```

### Malformed Bintray credential file

```
$ sandbox run 2.0.0-rc.2
Error: Malformed Bintray credentials in /Users/mj/.lightbend/commercial.credentials
Error: Please follow the instructions to setup the Lightbend Bintray credentials:
Error:   http://developers.lightbend.com/docs/reactive-platform/2.0/setup/setup-sbt.html
```

### Bintray unreachable

```
$ sandbox run 2.0.0-rc.2
Bintray credentials loaded from /Users/mj/.lightbend/commercial.credentials
Error: Artifact can not be resolved from Bintray.
Error: It seems that Bintray is unreachable.
Error: Please check your internet connection and try again.
```

### Conduct version not found on Bintray

```
$ sandbox run 2.10.0
Bintray credentials loaded from /Users/mj/.lightbend/commercial.credentials
Error: ConductR core 2.10.0 cannot be found on Bintray.
Error: Please specify a valid ConductR version.
Error: The latest version can be found on: https://www.lightbend.com/product/conductr/developer
```