Fixing docker error handling
The `sandbox run` command with ConductR 2.0.0  was failing with an exception if Docker was not installed. Docker is not required by Docker so it should not fail:

```
2017-02-01 18:41:14,908: Failure running the following command:
['sandbox', 'run', '2.0.0', '-n', '3', '--feature', 'visuali
zation']
Traceback (most recent call last):
File "conductr_cli/main_handler.py", line 14, in run
File "conductr_cli/sandbox.py", line 6, in main_method
File "conductr_cli/validation.py", line 407, in handler
File "conductr_cli/sandbox_main.py", line 224, in run
File "conductr_cli/validation.py", line 38, in handler
File "conductr_cli/validation.py", line 54, in handler
File "conductr_cli/validation.py", line 219, in handler
File "conductr_cli/validation.py", line 238, in handler
File "conductr_cli/validation.py", line 255, in handler
File "conductr_cli/validation.py", line 274, in handler
File "conductr_cli/validation.py", line 292, in handler
File "conductr_cli/validation.py", line 309, in handler
File "conductr_cli/validation.py", line 346, in handler
File "conductr_cli/validation.py", line 327, in handler
File "conductr_cli/validation.py", line 373, in handler
File "conductr_cli/validation.py", line 407, in handler
File "conductr_cli/sandbox_run.py", line 35, in run
File "conductr_cli/sandbox_run_jvm.py", line 64, in run
File "conductr_cli/sandbox_stop.py", line 6, in stop
File "conductr_cli/sandbox_proxy.py", line 50, in stop_proxy
File "conductr_cli/sandbox_proxy.py", line 83, in get_running_haproxy
File "conductr_cli/terminal.py", line 19, in docker_ps
File "subprocess.py", line 607, in check_output
File "subprocess.py", line 859, in __init__
File "subprocess.py", line 1457, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'docker'
```

The reason for the exception was that the `docker` command could not been found and therefore a `FileNotFoundError` was thrown. This error was not handled in the Docker validation.

This is PR is fixing this.