Handle ConductR startup errors
If ConductR has not been started within the 60 seconds then the `sandbox run` command will abort and display an improved error message:

```
$ sandbox run 2.0.2
|------------------------------------------------|
| Starting ConductR                              |
|------------------------------------------------|
Extracting ConductR core to /Users/mj/.conductr/images/core
Extracting ConductR agent to /Users/mj/.conductr/images/agent
Starting ConductR core instance on 192.168.10.1..
Waiting for ConductR to start.....
Error: ConductR has not been started within 10.0 seconds
Error: Set the env CONDUCTR_SANDBOX_WAIT_RETRIES to increase the wait timeout
Error: For more information check the ConductR log file at: /Users/mj/.conductr/images/core/logs/conductr.log
```

The error message got improved by adding the location of the log file (JVM mode only).

Prior to this PR, we have displayed an HTTP Connection error saying that the license could not be uploaded successfully. This was the case because we loaded the license on `sandbox run` and did not handled the ConductR startup error.